using System.ComponentModel;
using System.Globalization;
using ClipboardPal.Core.Abstractions;
using ClipboardPal.Core.Models;

namespace ClipboardPal.Core.Services;

/// <summary>Bindable indexer wrapper that refreshes when the UI language changes.</summary>
public sealed class LocView : INotifyPropertyChanged
{
    private readonly ILocalizationService _l10n;

    public LocView(ILocalizationService l10n)
    {
        _l10n = l10n;
        _l10n.LanguageChanged += () =>
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(string.Empty));
    }

    public string this[string key] => _l10n[key];

    public event PropertyChangedEventHandler? PropertyChanged;
}

public sealed class LocalizationService : ILocalizationService
{
    private Dictionary<string, string> _map = En;

    public event Action? LanguageChanged;

    public string this[string key] =>
        _map.TryGetValue(key, out var v) ? v : En.GetValueOrDefault(key, key);

    public void SetLanguage(UiLanguage language)
    {
        _map = Resolve(language);
        LanguageChanged?.Invoke();
    }

    private static Dictionary<string, string> Resolve(UiLanguage language) => language switch
    {
        UiLanguage.Russian => Ru,
        UiLanguage.German => De,
        UiLanguage.French => Fr,
        UiLanguage.Chinese => Zh,
        UiLanguage.Japanese => Ja,
        _ => En
    };

    // ----- English (default / fallback) -----
    private static readonly Dictionary<string, string> En = new()
    {
        ["app.name"] = "ClipboardPal",
        ["settings.title"] = "Settings",
        ["settings.window"] = "ClipboardPal — Settings",
        ["search.watermark"] = "Search…",
        ["btn.trash"] = "Trash",
        ["btn.clear"] = "Clear",
        ["btn.settings"] = "Settings",
        ["empty"] = "Clipboard history will appear here",
        ["empty.trash"] = "Trash is empty",
        ["tip.regex"] = "Regex search",
        ["tip.count"] = "Items in history",
        ["tip.queue"] = "Items in queue",
        ["tip.trash"] = "Show or hide trash",
        ["tip.settings"] = "Settings",
        ["tip.pin"] = "Pin",
        ["tip.queue.add"] = "Add to queue",
        ["tip.rename"] = "Rename",
        ["tip.delete"] = "Delete",
        ["tray.open"] = "Open panel",
        ["tray.settings"] = "Settings",
        ["tray.clear"] = "Clear history",
        ["tray.exit"] = "Quit",
        ["quit.confirm"] = "Quit ClipboardPal?",
        ["quit.yes"] = "Quit",
        ["quit.no"] = "Cancel",
        ["hotkey.press"] = "Press a shortcut… (Esc to cancel)",

        ["sec.language"] = "Language",
        ["row.language"] = "Interface language",
        ["hint.language"] = "English is the default. Changes apply immediately.",

        ["sec.enable"] = "Enable",
        ["row.monitor"] = "Watch clipboard",
        ["hint.monitor"] = "Capture new copies into history",

        ["sec.general"] = "General",
        ["row.autostart"] = "Launch at login",
        ["row.topmost"] = "Keep window on top",
        ["row.tray"] = "Show tray icon",
        ["row.dock"] = "Popup position",
        ["dock.left"] = "Left",
        ["dock.right"] = "Right",
        ["dock.top"] = "Top",
        ["dock.bottom"] = "Bottom",
        ["row.confirm.quit"] = "Confirm before quit",
        ["row.hide.outside"] = "Hide on outside click",
        ["row.updates"] = "Updates",
        ["btn.check"] = "Check",
        ["row.hotkey"] = "Panel hotkey",
        ["hint.hotkey"] = "Click and press a new shortcut. Esc cancels.",

        ["sec.copypaste"] = "Copy & Paste",
        ["row.sound"] = "Play sound on copy",
        ["row.sound.kind"] = "Sound",
        ["row.tray.anim"] = "Animate tray icon on copy",
        ["row.hide.after.copy"] = "Hide popup after copy",
        ["row.hide.after.paste"] = "Hide popup after paste",
        ["row.doubleclick"] = "Double-click",
        ["row.quickslots"] = "Win/Cmd + 1–9",

        ["sec.appearance"] = "Appearance",
        ["row.theme"] = "Theme",
        ["theme.dark"] = "Dark",
        ["theme.light"] = "Light",
        ["theme.system"] = "System",
        ["row.select.last"] = "Select last item",
        ["hint.select.last"] = "Select the latest clip when opening the panel",
        ["row.move.recent"] = "Move recent to top",
        ["hint.move.recent"] = "Move recently used clips to the top",
        ["row.card.menu"] = "Card menu buttons",
        ["hint.card.menu"] = "Show action buttons on each clip card",
        ["row.page.size"] = "Items per page",
        ["row.popup.limit"] = "Items in popup",
        ["row.preview.len"] = "Preview characters",

        ["sec.hotedge"] = "Hot edge",
        ["row.hotedge"] = "Hot edge",
        ["hint.hotedge"] = "Show the panel when the cursor rests on a screen edge",
        ["row.hotedge.delay"] = "Delay (sec)",

        ["sec.quickmode"] = "Quick mode",
        ["row.quickmode"] = "Quick mode",
        ["hint.quickmode"] = "Open the panel with the hotkey, press it again while holding modifiers to cycle clips, release to paste.",

        ["sec.queue"] = "Queue",
        ["row.queue"] = "Queue",
        ["hint.queue"] = "Temporary queue for collecting clips",
        ["row.queue.mode"] = "Paste mode",

        ["sec.plaintext"] = "Plain text",
        ["row.autoplain"] = "Auto plain text",
        ["hint.autoplain"] = "Strip formatting when copying",

        ["sec.data"] = "Data",
        ["row.skip.trash"] = "Skip trash",
        ["hint.skip.trash"] = "Delete immediately instead of moving to trash",
        ["row.ocr"] = "OCR on images",
        ["row.duplicates"] = "Save duplicates",
        ["row.images"] = "Save images",
        ["row.history.limit"] = "History limit",
        ["row.exclude"] = "Exclude apps",
        ["hint.exclude"] = "Process names, comma-separated: KeePass, Bitwarden",

        ["sec.link"] = "Links",
        ["row.link.preview"] = "Link previews",
        ["hint.link.preview"] = "Fetch title and description for new URLs",

        ["sec.search"] = "Search",
        ["row.case"] = "Case sensitive",
        ["hint.case"] = "Distinguish lower and upper case",
        ["row.regex"] = "Regular expression search",

        ["sec.history"] = "History",
        ["row.retention"] = "Keep history",
        ["hint.retention"] = "Older items are removed automatically",
        ["row.clear.all"] = "Clear all history",
        ["hint.clear.all"] = "Delete all items and data",
        ["btn.clear.all"] = "Clear",
        ["btn.reset"] = "Reset settings",

        ["sec.permissions"] = "Permissions",
        ["row.accessibility"] = "Accessibility",
        ["hint.accessibility"] = "Allow pasting into the active app",
        ["row.screen"] = "Screen Recording",
        ["hint.screen"] = "Required for image OCR",
        ["row.clipboard"] = "Clipboard access",
        ["hint.clipboard"] = "Allow reading the system clipboard",

        ["action.copy"] = "Copy",
        ["action.copy.plain"] = "Copy as plain text",
        ["action.paste"] = "Paste",
        ["action.paste.plain"] = "Paste as plain text",
        ["sound.default"] = "Default",
        ["sound.soft"] = "Soft",
        ["sound.click"] = "Click",
        ["sound.pop"] = "Pop",
    };

    private static readonly Dictionary<string, string> Ru = Merge(En, new()
    {
        ["settings.title"] = "Настройки",
        ["settings.window"] = "ClipboardPal — Настройки",
        ["search.watermark"] = "Поиск…",
        ["btn.trash"] = "Корзина",
        ["btn.clear"] = "Очистить",
        ["btn.settings"] = "Настройки",
        ["empty"] = "Здесь будет история буфера обмена",
        ["empty.trash"] = "Корзина пуста",
        ["tip.regex"] = "Regex-поиск",
        ["tip.count"] = "Элементов в истории",
        ["tip.queue"] = "Элементов в очереди",
        ["tip.trash"] = "Показать/скрыть корзину",
        ["tip.settings"] = "Настройки",
        ["tip.pin"] = "Закрепить",
        ["tip.queue.add"] = "В очередь",
        ["tip.rename"] = "Переименовать",
        ["tip.delete"] = "Удалить",
        ["tray.open"] = "Открыть панель",
        ["tray.settings"] = "Настройки",
        ["tray.clear"] = "Очистить историю",
        ["tray.exit"] = "Выход",
        ["quit.confirm"] = "Закрыть ClipboardPal?",
        ["quit.yes"] = "Выйти",
        ["quit.no"] = "Отмена",
        ["hotkey.press"] = "Нажмите сочетание… (Esc — отмена)",
        ["sec.language"] = "Язык",
        ["row.language"] = "Язык интерфейса",
        ["hint.language"] = "По умолчанию — английский. Применяется сразу.",
        ["sec.enable"] = "Включить",
        ["row.monitor"] = "Следить за буфером обмена",
        ["hint.monitor"] = "Захватывать новые копирования в историю",
        ["sec.general"] = "Основные",
        ["row.autostart"] = "Запускать при старте системы",
        ["row.topmost"] = "Держать окно поверх других",
        ["row.tray"] = "Показывать иконку в трее",
        ["row.dock"] = "Позиция всплывающего окна",
        ["dock.left"] = "Слева",
        ["dock.right"] = "Справа",
        ["dock.top"] = "Сверху",
        ["dock.bottom"] = "Снизу",
        ["row.confirm.quit"] = "Подтверждать перед выходом",
        ["row.hide.outside"] = "Скрывать при клике снаружи",
        ["row.updates"] = "Обновления",
        ["btn.check"] = "Проверить",
        ["row.hotkey"] = "Сочетание открытия панели",
        ["hint.hotkey"] = "Кликните и нажмите новое сочетание. Esc — отмена.",
        ["sec.copypaste"] = "Копирование и вставка",
        ["row.sound"] = "Звук при копировании",
        ["row.sound.kind"] = "Звук",
        ["row.tray.anim"] = "Анимация иконки трея при копировании",
        ["row.hide.after.copy"] = "Скрывать окно после копирования",
        ["row.hide.after.paste"] = "Скрывать окно после вставки",
        ["row.doubleclick"] = "Двойной клик",
        ["row.quickslots"] = "Win/Cmd + 1–9",
        ["sec.appearance"] = "Внешний вид",
        ["row.theme"] = "Тема",
        ["theme.dark"] = "Тёмная",
        ["theme.light"] = "Светлая",
        ["theme.system"] = "Системная",
        ["row.select.last"] = "Выделять последний",
        ["hint.select.last"] = "Выделять последний клип при открытии панели",
        ["row.move.recent"] = "Выделять недавний",
        ["hint.move.recent"] = "Перемещать недавно использованный клип вверх",
        ["row.card.menu"] = "Кнопки меню на карточке",
        ["hint.card.menu"] = "Показать кнопки действий на клипе",
        ["row.page.size"] = "Элементов на странице",
        ["row.popup.limit"] = "Элементов во всплывающем окне",
        ["row.preview.len"] = "Символов в превью карточки",
        ["sec.hotedge"] = "Горячий край",
        ["row.hotedge"] = "Горячий край",
        ["hint.hotedge"] = "Показать панель при наведении на край экрана",
        ["row.hotedge.delay"] = "Задержка (сек)",
        ["sec.quickmode"] = "Быстрый режим",
        ["row.quickmode"] = "Быстрый режим",
        ["hint.quickmode"] = "Откройте панель хоткеем, нажмите его снова с удержанием модификаторов для переключения клипов, отпустите для вставки.",
        ["sec.queue"] = "Очередь",
        ["row.queue"] = "Очередь",
        ["hint.queue"] = "Временная очередь для сбора клипов",
        ["row.queue.mode"] = "Режим вставки",
        ["sec.plaintext"] = "Обычный текст",
        ["row.autoplain"] = "Авто простой текст",
        ["hint.autoplain"] = "Убирать форматирование при копировании",
        ["sec.data"] = "Данные",
        ["row.skip.trash"] = "Пропустить корзину",
        ["hint.skip.trash"] = "Удалять сразу, без корзины",
        ["row.ocr"] = "OCR на изображениях",
        ["row.duplicates"] = "Сохранять дубликаты",
        ["row.images"] = "Сохранять изображения",
        ["row.history.limit"] = "Лимит истории",
        ["row.exclude"] = "Исключить приложения",
        ["hint.exclude"] = "Имена процессов через запятую: KeePass, Bitwarden",
        ["sec.link"] = "Ссылки",
        ["row.link.preview"] = "Превью ссылок",
        ["hint.link.preview"] = "Загружать заголовок и описание для новых URL",
        ["sec.search"] = "Поиск",
        ["row.case"] = "Учитывать регистр",
        ["hint.case"] = "Различать строчные и заглавные буквы",
        ["row.regex"] = "Поиск по регулярным выражениям",
        ["sec.history"] = "История",
        ["row.retention"] = "Хранить историю",
        ["hint.retention"] = "Более старые элементы удаляются автоматически",
        ["row.clear.all"] = "Очистить всю историю",
        ["hint.clear.all"] = "Удалить все данные и элементы",
        ["btn.clear.all"] = "Очистить",
        ["btn.reset"] = "Сбросить настройки",
        ["sec.permissions"] = "Разрешения",
        ["row.accessibility"] = "Accessibility",
        ["hint.accessibility"] = "Разрешить вставку в активное приложение",
        ["row.screen"] = "Screen Recording",
        ["hint.screen"] = "Нужно для OCR изображений",
        ["row.clipboard"] = "Чтение буфера",
        ["hint.clipboard"] = "Разрешить читать буфер обмена",
        ["action.copy"] = "Скопировать",
        ["action.copy.plain"] = "Скопировать как простой текст",
        ["action.paste"] = "Вставить",
        ["action.paste.plain"] = "Вставить как простой текст",
        ["sound.default"] = "По умолчанию",
        ["sound.soft"] = "Мягкий",
        ["sound.click"] = "Клик",
        ["sound.pop"] = "Pop",
    });

    private static readonly Dictionary<string, string> De = Merge(En, new()
    {
        ["settings.title"] = "Einstellungen",
        ["settings.window"] = "ClipboardPal — Einstellungen",
        ["search.watermark"] = "Suchen…",
        ["btn.trash"] = "Papierkorb",
        ["btn.clear"] = "Leeren",
        ["btn.settings"] = "Einstellungen",
        ["empty"] = "Die Zwischenablage-Historie erscheint hier",
        ["empty.trash"] = "Papierkorb ist leer",
        ["tip.regex"] = "Regex-Suche",
        ["tip.count"] = "Einträge im Verlauf",
        ["tip.queue"] = "Einträge in der Warteschlange",
        ["tip.trash"] = "Papierkorb ein-/ausblenden",
        ["tip.settings"] = "Einstellungen",
        ["tip.pin"] = "Anheften",
        ["tip.queue.add"] = "Zur Warteschlange",
        ["tip.rename"] = "Umbenennen",
        ["tip.delete"] = "Löschen",
        ["tray.open"] = "Panel öffnen",
        ["tray.settings"] = "Einstellungen",
        ["tray.clear"] = "Verlauf löschen",
        ["tray.exit"] = "Beenden",
        ["quit.confirm"] = "ClipboardPal beenden?",
        ["quit.yes"] = "Beenden",
        ["quit.no"] = "Abbrechen",
        ["hotkey.press"] = "Tastenkürzel drücken… (Esc zum Abbrechen)",
        ["sec.language"] = "Sprache",
        ["row.language"] = "Oberflächensprache",
        ["hint.language"] = "Englisch ist Standard. Änderungen gelten sofort.",
        ["sec.enable"] = "Aktivieren",
        ["row.monitor"] = "Zwischenablage überwachen",
        ["hint.monitor"] = "Neue Kopien in den Verlauf übernehmen",
        ["sec.general"] = "Allgemein",
        ["row.autostart"] = "Beim Anmelden starten",
        ["row.topmost"] = "Fenster im Vordergrund halten",
        ["row.tray"] = "Tray-Symbol anzeigen",
        ["row.dock"] = "Position des Popups",
        ["dock.left"] = "Links",
        ["dock.right"] = "Rechts",
        ["dock.top"] = "Oben",
        ["dock.bottom"] = "Unten",
        ["row.confirm.quit"] = "Vor dem Beenden bestätigen",
        ["row.hide.outside"] = "Bei Klick außerhalb ausblenden",
        ["row.updates"] = "Updates",
        ["btn.check"] = "Prüfen",
        ["row.hotkey"] = "Panel-Hotkey",
        ["hint.hotkey"] = "Klicken und neues Kürzel drücken. Esc bricht ab.",
        ["sec.copypaste"] = "Kopieren & Einfügen",
        ["row.sound"] = "Ton beim Kopieren",
        ["row.sound.kind"] = "Ton",
        ["row.tray.anim"] = "Tray-Animation beim Kopieren",
        ["row.hide.after.copy"] = "Popup nach Kopieren ausblenden",
        ["row.hide.after.paste"] = "Popup nach Einfügen ausblenden",
        ["row.doubleclick"] = "Doppelklick",
        ["sec.appearance"] = "Darstellung",
        ["row.theme"] = "Design",
        ["theme.dark"] = "Dunkel",
        ["theme.light"] = "Hell",
        ["theme.system"] = "System",
        ["sec.hotedge"] = "Hot Edge",
        ["sec.quickmode"] = "Schnellmodus",
        ["sec.queue"] = "Warteschlange",
        ["sec.plaintext"] = "Klartext",
        ["sec.data"] = "Daten",
        ["sec.link"] = "Links",
        ["sec.search"] = "Suche",
        ["sec.history"] = "Verlauf",
        ["sec.permissions"] = "Berechtigungen",
        ["btn.reset"] = "Einstellungen zurücksetzen",
        ["btn.clear.all"] = "Leeren",
        ["action.copy"] = "Kopieren",
        ["action.paste"] = "Einfügen",
    });

    private static readonly Dictionary<string, string> Fr = Merge(En, new()
    {
        ["settings.title"] = "Paramètres",
        ["settings.window"] = "ClipboardPal — Paramètres",
        ["search.watermark"] = "Rechercher…",
        ["btn.trash"] = "Corbeille",
        ["btn.clear"] = "Effacer",
        ["btn.settings"] = "Paramètres",
        ["empty"] = "L’historique du presse-papiers apparaîtra ici",
        ["empty.trash"] = "La corbeille est vide",
        ["tip.regex"] = "Recherche regex",
        ["tip.count"] = "Éléments dans l’historique",
        ["tip.queue"] = "Éléments dans la file",
        ["tip.trash"] = "Afficher/masquer la corbeille",
        ["tip.settings"] = "Paramètres",
        ["tip.pin"] = "Épingler",
        ["tip.queue.add"] = "Ajouter à la file",
        ["tip.rename"] = "Renommer",
        ["tip.delete"] = "Supprimer",
        ["tray.open"] = "Ouvrir le panneau",
        ["tray.settings"] = "Paramètres",
        ["tray.clear"] = "Effacer l’historique",
        ["tray.exit"] = "Quitter",
        ["quit.confirm"] = "Quitter ClipboardPal ?",
        ["quit.yes"] = "Quitter",
        ["quit.no"] = "Annuler",
        ["hotkey.press"] = "Appuyez sur un raccourci… (Échap pour annuler)",
        ["sec.language"] = "Langue",
        ["row.language"] = "Langue de l’interface",
        ["hint.language"] = "L’anglais est la langue par défaut. Les changements s’appliquent immédiatement.",
        ["sec.enable"] = "Activer",
        ["row.monitor"] = "Surveiller le presse-papiers",
        ["hint.monitor"] = "Enregistrer les nouvelles copies dans l’historique",
        ["sec.general"] = "Général",
        ["row.autostart"] = "Lancer à la connexion",
        ["row.topmost"] = "Garder la fenêtre au premier plan",
        ["row.tray"] = "Afficher l’icône dans la barre",
        ["row.dock"] = "Position du panneau",
        ["dock.left"] = "Gauche",
        ["dock.right"] = "Droite",
        ["dock.top"] = "Haut",
        ["dock.bottom"] = "Bas",
        ["row.confirm.quit"] = "Confirmer avant de quitter",
        ["row.hide.outside"] = "Masquer au clic extérieur",
        ["row.updates"] = "Mises à jour",
        ["btn.check"] = "Vérifier",
        ["row.hotkey"] = "Raccourci du panneau",
        ["sec.copypaste"] = "Copier & coller",
        ["sec.appearance"] = "Apparence",
        ["row.theme"] = "Thème",
        ["theme.dark"] = "Sombre",
        ["theme.light"] = "Clair",
        ["theme.system"] = "Système",
        ["sec.hotedge"] = "Bord chaud",
        ["sec.quickmode"] = "Mode rapide",
        ["sec.queue"] = "File",
        ["sec.plaintext"] = "Texte brut",
        ["sec.data"] = "Données",
        ["sec.link"] = "Liens",
        ["sec.search"] = "Recherche",
        ["sec.history"] = "Historique",
        ["sec.permissions"] = "Autorisations",
        ["btn.reset"] = "Réinitialiser les paramètres",
        ["btn.clear.all"] = "Effacer",
        ["action.copy"] = "Copier",
        ["action.paste"] = "Coller",
    });

    private static readonly Dictionary<string, string> Zh = Merge(En, new()
    {
        ["settings.title"] = "设置",
        ["settings.window"] = "ClipboardPal — 设置",
        ["search.watermark"] = "搜索…",
        ["btn.trash"] = "回收站",
        ["btn.clear"] = "清除",
        ["btn.settings"] = "设置",
        ["empty"] = "剪贴板历史将显示在这里",
        ["empty.trash"] = "回收站为空",
        ["tip.regex"] = "正则搜索",
        ["tip.count"] = "历史条目数",
        ["tip.queue"] = "队列条目数",
        ["tip.trash"] = "显示/隐藏回收站",
        ["tip.settings"] = "设置",
        ["tip.pin"] = "固定",
        ["tip.queue.add"] = "加入队列",
        ["tip.rename"] = "重命名",
        ["tip.delete"] = "删除",
        ["tray.open"] = "打开面板",
        ["tray.settings"] = "设置",
        ["tray.clear"] = "清除历史",
        ["tray.exit"] = "退出",
        ["quit.confirm"] = "退出 ClipboardPal？",
        ["quit.yes"] = "退出",
        ["quit.no"] = "取消",
        ["hotkey.press"] = "请按下快捷键…（Esc 取消）",
        ["sec.language"] = "语言",
        ["row.language"] = "界面语言",
        ["hint.language"] = "默认英语。更改立即生效。",
        ["sec.enable"] = "启用",
        ["row.monitor"] = "监视剪贴板",
        ["hint.monitor"] = "将新的复制内容保存到历史记录",
        ["sec.general"] = "常规",
        ["row.autostart"] = "登录时启动",
        ["row.topmost"] = "窗口置顶",
        ["row.tray"] = "显示托盘图标",
        ["row.dock"] = "弹出面板位置",
        ["dock.left"] = "左侧",
        ["dock.right"] = "右侧",
        ["dock.top"] = "顶部",
        ["dock.bottom"] = "底部",
        ["row.confirm.quit"] = "退出前确认",
        ["row.hide.outside"] = "点击外部时隐藏",
        ["row.updates"] = "更新",
        ["btn.check"] = "检查",
        ["row.hotkey"] = "面板快捷键",
        ["sec.copypaste"] = "复制与粘贴",
        ["sec.appearance"] = "外观",
        ["row.theme"] = "主题",
        ["theme.dark"] = "深色",
        ["theme.light"] = "浅色",
        ["theme.system"] = "跟随系统",
        ["sec.hotedge"] = "热边缘",
        ["sec.quickmode"] = "快速模式",
        ["sec.queue"] = "队列",
        ["sec.plaintext"] = "纯文本",
        ["sec.data"] = "数据",
        ["sec.link"] = "链接",
        ["sec.search"] = "搜索",
        ["sec.history"] = "历史",
        ["sec.permissions"] = "权限",
        ["btn.reset"] = "重置设置",
        ["btn.clear.all"] = "清除",
        ["action.copy"] = "复制",
        ["action.paste"] = "粘贴",
    });

    private static readonly Dictionary<string, string> Ja = Merge(En, new()
    {
        ["settings.title"] = "設定",
        ["settings.window"] = "ClipboardPal — 設定",
        ["search.watermark"] = "検索…",
        ["btn.trash"] = "ゴミ箱",
        ["btn.clear"] = "クリア",
        ["btn.settings"] = "設定",
        ["empty"] = "クリップボード履歴がここに表示されます",
        ["empty.trash"] = "ゴミ箱は空です",
        ["tip.regex"] = "正規表現検索",
        ["tip.count"] = "履歴の件数",
        ["tip.queue"] = "キューの件数",
        ["tip.trash"] = "ゴミ箱の表示切替",
        ["tip.settings"] = "設定",
        ["tip.pin"] = "ピン留め",
        ["tip.queue.add"] = "キューに追加",
        ["tip.rename"] = "名前変更",
        ["tip.delete"] = "削除",
        ["tray.open"] = "パネルを開く",
        ["tray.settings"] = "設定",
        ["tray.clear"] = "履歴をクリア",
        ["tray.exit"] = "終了",
        ["quit.confirm"] = "ClipboardPal を終了しますか？",
        ["quit.yes"] = "終了",
        ["quit.no"] = "キャンセル",
        ["hotkey.press"] = "ショートカットを押してください…（Esc でキャンセル）",
        ["sec.language"] = "言語",
        ["row.language"] = "インターフェース言語",
        ["hint.language"] = "デフォルトは英語です。変更はすぐに反映されます。",
        ["sec.enable"] = "有効",
        ["row.monitor"] = "クリップボードを監視",
        ["hint.monitor"] = "新しいコピーを履歴に保存",
        ["sec.general"] = "一般",
        ["row.autostart"] = "ログイン時に起動",
        ["row.topmost"] = "常に手前に表示",
        ["row.tray"] = "トレイアイコンを表示",
        ["row.dock"] = "パネルの位置",
        ["dock.left"] = "左",
        ["dock.right"] = "右",
        ["dock.top"] = "上",
        ["dock.bottom"] = "下",
        ["row.confirm.quit"] = "終了前に確認",
        ["row.hide.outside"] = "外側クリックで隠す",
        ["row.updates"] = "アップデート",
        ["btn.check"] = "確認",
        ["row.hotkey"] = "パネルのホットキー",
        ["sec.copypaste"] = "コピー＆ペースト",
        ["sec.appearance"] = "外観",
        ["row.theme"] = "テーマ",
        ["theme.dark"] = "ダーク",
        ["theme.light"] = "ライト",
        ["theme.system"] = "システム",
        ["sec.hotedge"] = "ホットエッジ",
        ["sec.quickmode"] = "クイックモード",
        ["sec.queue"] = "キュー",
        ["sec.plaintext"] = "プレーンテキスト",
        ["sec.data"] = "データ",
        ["sec.link"] = "リンク",
        ["sec.search"] = "検索",
        ["sec.history"] = "履歴",
        ["sec.permissions"] = "権限",
        ["btn.reset"] = "設定をリセット",
        ["btn.clear.all"] = "クリア",
        ["action.copy"] = "コピー",
        ["action.paste"] = "ペースト",
    });

    private static Dictionary<string, string> Merge(
        Dictionary<string, string> baseline,
        Dictionary<string, string> overlay)
    {
        var map = new Dictionary<string, string>(baseline, StringComparer.Ordinal);
        foreach (var (k, v) in overlay)
            map[k] = v;
        return map;
    }
}
